version: 2
updates:
  # ✅ Keep pnpm (npm-based) dependencies up to date (including security updates)
  - package-ecosystem: "npm"
    directory: "/"  # Root directory
    schedule:
      interval: "weekly"
      time: "06:00"  # Runs every week at 6 AM UTC
    open-pull-requests-limit: 5
    versioning-strategy: "increase"
    assignees:
      - "dustin-lennon"
    reviewers:
      - "dustin-lennon"
    labels:
      - "dependencies"
      - "pnpm"
    ignore:
      - dependency-name: "typescript"
        versions: ["<5.0.0"]
    commit-message:
      prefix: "deps"
      include: "scope"
    allow:
      - dependency-type: "direct"
    automerge:
      strategy: "squash"
      commit-message:
        prefix: "chore"
        include: "scope"
      ignore:
        - update-type: "version-update:semver-major"

  # ✅ Keep GitHub Actions dependencies up to date
  - package-ecosystem: "github-actions"
    directory: "/"  
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 3
    assignees:
      - "dustin-lennon"
    reviewers:
      - "dustin-lennon"
    labels:
      - "dependencies"
      - "github-actions"
    automerge:
      strategy: "squash"
      commit-message:
        prefix: "chore"
        include: "scope"

  # ✅ Keep Docker dependencies updated (if applicable)
  - package-ecosystem: "docker"
    directory: "/"  
    schedule:
      interval: "weekly"
      time: "06:00"
    open-pull-requests-limit: 3
    assignees:
      - "dustin-lennon"
    reviewers:
      - "dustin-lennon"
    labels:
      - "dependencies"
      - "docker"
    automerge:
      strategy: "squash"
      commit-message:
        prefix: "chore"
        include: "scope"

  # ✅ Keep Security Updates Automatically Applied (only minor and patch updates)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 5
    labels:
      - "security"
      - "pnpm"
    reviewers:
      - "dustin-lennon"
    assignees:
      - "dustin-lennon"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "eslint"
    automerge:
      strategy: "squash"
      commit-message:
        prefix: "chore"
        include: "scope"
      ignore:
        - update-type: "version-update:semver-major"
