name: Back Merge main to develop

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual trigger too

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-main-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '🔄 Sync main to develop'
          body: 'Automated back-merge from `main` to `develop`.'
          base: develop
          branch: sync/main-to-develop
          delete-branch: true
          draft: false
          branch-suffix: timestamp

      - name: Auto-merge PR if checks pass
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Waiting for GitHub to start checks..."
          sleep 30

          PR_NUMBER=$(gh pr list --head sync/main-to-develop --state open --json number --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "No PR found to auto-merge."
            exit 1
          fi

          gh pr merge $PR_NUMBER --merge --auto --delete-branch
