name: Back Merge main to develop

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  merge-main-to-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Check if PR already exists
        id: check_pr
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:sync/main-to-develop`,
              base: 'develop',
              state: 'open'
            });
            return prs.length > 0;

      - name: Create Pull Request
        if: steps.check_pr.outputs.result == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: '🔄 Sync main to develop'
          body: 'Automated back-merge from `main` to `develop`.'
          base: develop
          branch: sync/main-to-develop
          delete-branch: true
          draft: false

      - name: Auto-merge PR if checks pass
        if: steps.check_pr.outputs.result == 'false'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Waiting for checks to initialize..."
          sleep 30

          PR_NUMBER=$(gh pr list --head sync/main-to-develop --json number --jq '.[0].number')

          if [ -z "$PR_NUMBER" ]; then
            echo "❌ No PR found to auto-merge."
            exit 1
          fi

          gh pr merge $PR_NUMBER --merge --auto --delete-branch
