name: Delete Merged Feature, Hotfix, and Bugfix Branches

on:
  pull_request:
    types: [closed]

jobs:
  delete-merged-branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    steps:
      - name: Check if PR was merged
        if: github.event.pull_request.merged == true
        run: echo "✅ PR was merged. Checking branch name..."

      - name: Delete `feature/*`, `hotfix/*`, and `bugfix/*` branches
        if: github.event.pull_request.merged == true &&
          (startsWith(github.event.pull_request.head.ref, 'feature/') ||
           startsWith(github.event.pull_request.head.ref, 'hotfix/') ||
           startsWith(github.event.pull_request.head.ref, 'bugfix/'))
        run: |
          BRANCH_NAME=${{ github.event.pull_request.head.ref }}
          echo "🚀 Attempting to delete branch: $BRANCH_NAME"

          curl -X DELETE -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/${{ github.repository }}/git/refs/heads/$BRANCH_NAME"
